name: CI Pipeline

on:
  push:
    branches: [cicd-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Dockerhub
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        run: docker build -t image-test .

      - name: taging
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        run: docker tag image-test:latest $DOCKER_USERNAME/image-test:latest

      - name: Push to Dockerhub
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        run: docker push $DOCKER_USERNAME/image-test:latest
